require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoordenadoresController do

  # This should return the minimal set of attributes required to create a valid
  # Coordenador. As you add validations to Coordenador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoordenadoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coordenadores as @coordenadores" do
      coordenador = Coordenador.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coordenadores).should eq([coordenador])
    end
  end

  describe "GET show" do
    it "assigns the requested coordenador as @coordenador" do
      coordenador = Coordenador.create! valid_attributes
      get :show, {:id => coordenador.to_param}, valid_session
      assigns(:coordenador).should eq(coordenador)
    end
  end

  describe "GET new" do
    it "assigns a new coordenador as @coordenador" do
      get :new, {}, valid_session
      assigns(:coordenador).should be_a_new(Coordenador)
    end
  end

  describe "GET edit" do
    it "assigns the requested coordenador as @coordenador" do
      coordenador = Coordenador.create! valid_attributes
      get :edit, {:id => coordenador.to_param}, valid_session
      assigns(:coordenador).should eq(coordenador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coordenador" do
        expect {
          post :create, {:coordenador => valid_attributes}, valid_session
        }.to change(Coordenador, :count).by(1)
      end

      it "assigns a newly created coordenador as @coordenador" do
        post :create, {:coordenador => valid_attributes}, valid_session
        assigns(:coordenador).should be_a(Coordenador)
        assigns(:coordenador).should be_persisted
      end

      it "redirects to the created coordenador" do
        post :create, {:coordenador => valid_attributes}, valid_session
        response.should redirect_to(Coordenador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coordenador as @coordenador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coordenador.any_instance.stub(:save).and_return(false)
        post :create, {:coordenador => { "nome" => "invalid value" }}, valid_session
        assigns(:coordenador).should be_a_new(Coordenador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coordenador.any_instance.stub(:save).and_return(false)
        post :create, {:coordenador => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coordenador" do
        coordenador = Coordenador.create! valid_attributes
        # Assuming there are no other coordenadores in the database, this
        # specifies that the Coordenador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coordenador.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => coordenador.to_param, :coordenador => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested coordenador as @coordenador" do
        coordenador = Coordenador.create! valid_attributes
        put :update, {:id => coordenador.to_param, :coordenador => valid_attributes}, valid_session
        assigns(:coordenador).should eq(coordenador)
      end

      it "redirects to the coordenador" do
        coordenador = Coordenador.create! valid_attributes
        put :update, {:id => coordenador.to_param, :coordenador => valid_attributes}, valid_session
        response.should redirect_to(coordenador)
      end
    end

    describe "with invalid params" do
      it "assigns the coordenador as @coordenador" do
        coordenador = Coordenador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coordenador.any_instance.stub(:save).and_return(false)
        put :update, {:id => coordenador.to_param, :coordenador => { "nome" => "invalid value" }}, valid_session
        assigns(:coordenador).should eq(coordenador)
      end

      it "re-renders the 'edit' template" do
        coordenador = Coordenador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coordenador.any_instance.stub(:save).and_return(false)
        put :update, {:id => coordenador.to_param, :coordenador => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coordenador" do
      coordenador = Coordenador.create! valid_attributes
      expect {
        delete :destroy, {:id => coordenador.to_param}, valid_session
      }.to change(Coordenador, :count).by(-1)
    end

    it "redirects to the coordenadores list" do
      coordenador = Coordenador.create! valid_attributes
      delete :destroy, {:id => coordenador.to_param}, valid_session
      response.should redirect_to(coordenadores_url)
    end
  end

end
